name: Test Slack Notifications
on:
  workflow_dispatch:
jobs:
  go-tests:
    name: Slack Notifications Tests
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_CHANNEL: dig-phantom-core
          SLACK_USERNAME: runners
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
